name: Publish Docker Production Image

on:
  push:
    branches:
      - release/*

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Docker tag from branch name
        id: extract-tag
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          DOCKER_TAG=${BRANCH_NAME#*/}
          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1


      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: webapp
        run: |
          export DOCKER_IMAGE_NAME=$ECR_REGISTRY/$ECR_REPOSITORY
        
          # Build with the extracted tag
          docker build -t $DOCKER_IMAGE_NAME:$DOCKER_TAG .
          echo $DOCKER_IMAGE_NAME:$DOCKER_TAG
          docker push $DOCKER_IMAGE_NAME:$DOCKER_TAG