name: deploy to ECR

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
      - name: "Build And Publish"
        run: |
          docker build . --tag webapp:latest
